# palworldのiniを修正した場合に実施するタスク
- name: update palworld ini
  hosts: _vm_palworld
  vars_files:
    - group_vars/all.yml
    - group_vars/secret.yml
  roles:
    - palworld/server_stop
    - palworld/backup
    - palworld/setting_ini
    - palworld/server_start